### ISSUE TITLE
Error in running train.py

### ISSUE THREAD

**Issue by mmcghee18** [Grzego/handwriting-generation#7]
Hi! 👋 

I'm following your instructions in README.md to get things running. For context: I'm running on a Microsoft Azure GPU, using Tensorflow 1.5 and Python 3.5. When I run `python train.py`, I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/jameso2/handwriting-generation/.env/local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/jameso2/handwriting-generation/.env/local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/jameso2/handwriting-generation/.env/local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/jameso2/handwriting-generation/.env/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/jameso2/handwriting-generation/.env/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```

What could be causing this?

Thank you for this awesome work! 😊

**Comment by Grzego** [comment]
Hi! 

It looks like a problem with CUDA version. As far as I remember TensorFlow 1.5 uses CUDA 9.0 in prebuild binaries (from PyPl), so make sure you have this version installed on your machine. Let me know if that was the issue. :smiley:

**Comment by mmcghee18** [comment]
Thank you, that worked!

**Comment by Grzego** [comment]
That's great! :smile:
