### ISSUE TITLE
Trouble displaying output

### ISSUE THREAD

**Issue by jameso2** [Grzego/handwriting-generation#8]
I am following the instructions in the README to generate handwriting. When I enter the command: 
`python generate.py --noinfo --text="this was generated by computer" --bias=1.`

I get the following error:

> Traceback (most recent call last):
  File "generate.py", line 247, in <module>
    main()
  File "generate.py", line 202, in main
    fig, ax = plt.subplots(1, 1)
  File "/home/jameso2/handwriting-generation/.env/local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 1176, in subplots
    fig = figure(**fig_kw)
  File "/home/jameso2/handwriting-generation/.env/local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 539, in figure
    **kwargs)
  File "/home/jameso2/handwriting-generation/.env/local/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 171, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/jameso2/handwriting-generation/.env/local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1871, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

For context, I am running the code on a Linux virtual machine with Ubuntu. My laptop is a MacBook.

Any idea how to resolve this? I'd appreciate any help!

**Comment by Grzego** [comment]
Hi, do you have any displays for that virtual machine or you are using it from terminal? In case of the latter you would have to modify code so that it only saves image to file (look at [this](https://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined) and [this](https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server) stackoverflow questions). :)

**Comment by jameso2** [comment]
That worked, thanks for the help!

**Comment by Grzego** [comment]
Great! :)
